### ISSUE TITLE
please port to Sublime Text 3

### ISSUE THREAD

**Issue by vitaly-zdanevich** [alek-sys/ChangeTracker#8]

**Comment by alek-sys** [comment]
It actually works in ST3, just not available via PackageControl.io.
You can install it manually though:
1. In ST3 click Preferences - Browse Packages, this will give you a folder where packages are stored
2. Clone ChangesTracker into this folder - open command line, cd to folder from step 1 and do 

```
git clone https://github.com/alek-sys/ChangeTracker.git
```

Plugin then should be available. But please note I'm not actively support it now, so cannot promise any updates or maintenance.
